# Generated by Django 4.2.30 on 2026-09-16 02:56

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('work_type', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractorContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_date', models.DateField()),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField()),
                ('expense_category', models.CharField(choices=[('LABOUR', 'Labour'), ('CONTRACTOR', 'Contractor'), ('SUPPLIER', 'Supplier'), ('MISCELLANEOUS', 'Miscellaneous')], max_length=20)),
                ('expense_type', models.CharField(help_text='Free text, validated against expense_category in clean().', max_length=100)),
                ('party_type', models.CharField(choices=[('LABOUR', 'Labour'), ('CONTRACTOR', 'Contractor'), ('SUPPLIER', 'Supplier'), ('NONE', 'None')], default='NONE', max_length=20)),
                ('payee_name', models.CharField(blank=True, help_text='Used for MISCELLANEOUS expenses.', max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('UPI', 'UPI'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], max_length=20)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Labour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_date', models.DateField()),
                ('fund_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('UPI', 'UPI'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManagerLabourDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MiscExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('plot_size', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed')], default='PLANNED', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('supplier_type', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to='core.owner')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_owners', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_projects', to='core.manager')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_managers', to='core.project')),
            ],
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='core_projec_status_2020cc_idx'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managerlabourdistribution',
            name='expense_transaction',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manager_labour_distribution', to='core.expensetransaction'),
        ),
        migrations.AddField(
            model_name='managerlabourdistribution',
            name='labour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager_distributions', to='core.labour'),
        ),
        migrations.AddField(
            model_name='managerlabourdistribution',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_distributions', to='core.manager'),
        ),
        migrations.AddField(
            model_name='managerlabourdistribution',
            name='manager_fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributions', to='core.managerfund'),
        ),
        migrations.AddField(
            model_name='managerlabourdistribution',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_labour_distributions', to='core.project'),
        ),
        migrations.AddField(
            model_name='managerfund',
            name='given_by_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager_funds_given', to='core.owner'),
        ),
        migrations.AddField(
            model_name='managerfund',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds_received', to='core.manager'),
        ),
        migrations.AddField(
            model_name='managerfund',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_funds', to='core.project'),
        ),
        migrations.AddField(
            model_name='manager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='contractor_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_transactions', to='core.contractorcontract'),
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_transactions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='labour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_transactions', to='core.labour'),
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_transactions_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='paid_by_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_transactions', to='core.owner'),
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_transactions', to='core.project'),
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_transactions', to='core.supplier'),
        ),
        migrations.AddField(
            model_name='contractorcontract',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='core.contractor'),
        ),
        migrations.AddField(
            model_name='contractorcontract',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_contracts', to='core.project'),
        ),
        migrations.AddIndex(
            model_name='projectowner',
            index=models.Index(fields=['project'], name='core_projec_project_9ff930_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectowner',
            unique_together={('project', 'owner')},
        ),
        migrations.AddIndex(
            model_name='projectmanager',
            index=models.Index(fields=['project'], name='core_projec_project_71ce72_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmanager',
            unique_together={('project', 'manager')},
        ),
        migrations.AddIndex(
            model_name='managerlabourdistribution',
            index=models.Index(fields=['project'], name='core_manage_project_04f1c6_idx'),
        ),
        migrations.AddIndex(
            model_name='managerlabourdistribution',
            index=models.Index(fields=['date'], name='core_manage_date_7d47bd_idx'),
        ),
        migrations.AddIndex(
            model_name='managerfund',
            index=models.Index(fields=['project'], name='core_manage_project_36fa6b_idx'),
        ),
        migrations.AddIndex(
            model_name='managerfund',
            index=models.Index(fields=['fund_date'], name='core_manage_fund_da_222a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='expensetransaction',
            index=models.Index(fields=['project'], name='core_expens_project_bee5e9_idx'),
        ),
        migrations.AddIndex(
            model_name='expensetransaction',
            index=models.Index(fields=['expense_date'], name='core_expens_expense_bd1fad_idx'),
        ),
        migrations.AddIndex(
            model_name='expensetransaction',
            index=models.Index(fields=['project', 'expense_date'], name='core_expens_project_f51ce3_idx'),
        ),
        migrations.AddIndex(
            model_name='expensetransaction',
            index=models.Index(fields=['expense_category'], name='core_expens_expense_b97db2_idx'),
        ),
        migrations.AddIndex(
            model_name='expensetransaction',
            index=models.Index(fields=['status'], name='core_expens_status_3c44c6_idx'),
        ),
        migrations.AddIndex(
            model_name='contractorcontract',
            index=models.Index(fields=['project'], name='core_contra_project_6aadd3_idx'),
        ),
        migrations.AddIndex(
            model_name='contractorcontract',
            index=models.Index(fields=['contract_date'], name='core_contra_contrac_c801de_idx'),
        ),
    ]
