# Generated by Django 4.2.30 on 2026-09-19 11:31

from django.db import migrations, models
import django.db.models.deletion


def backfill_project_labour(apps, schema_editor):
    """
    Payment history is evidence of an earlier association, so link every (project,
    labour) pair that has at least one NON-CANCELLED Labour payment. All are created
    ACTIVE: current working status is an explicit choice (mark inactive), never
    inferred from how old the last payment is. Pairs with only CANCELLED payments get
    no row. Nothing existing is changed or deleted.
    """
    ExpenseTransaction = apps.get_model('core', 'ExpenseTransaction')
    ProjectLabour = apps.get_model('core', 'ProjectLabour')
    pairs = (
        ExpenseTransaction.objects.filter(labour__isnull=False)
        .exclude(status='CANCELLED')
        .values_list('project_id', 'labour_id').distinct()
    )
    ProjectLabour.objects.bulk_create(
        [ProjectLabour(project_id=project_id, labour_id=labour_id, is_active=True) for project_id, labour_id in pairs],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetransaction',
            name='payment_batch',
            field=models.UUIDField(blank=True, db_index=True, editable=False, help_text='Shared by the per-labour rows saved together from one Labour Payment entry.', null=True),
        ),
        migrations.CreateModel(
            name='ProjectLabour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='core.labour')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_labours', to='core.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'is_active'], name='core_projec_project_556226_idx')],
                'unique_together': {('project', 'labour')},
            },
        ),
        migrations.RunPython(backfill_project_labour, migrations.RunPython.noop),
    ]
