# Generated by Django 4.2.30 on 2026-09-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_labour_and_payment_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorcontract',
            name='work_description',
            field=models.CharField(blank=True, default='', help_text='What this contract covers. One contractor may have several contracts on a project, so this (with the amount) tells them apart. Required by the API.', max_length=255),
        ),
    ]
