# Generated by Django 4.2.30 on 2026-09-20 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_contractorcontract_work_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerfund',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manager_funds_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managerlabourdistribution',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manager_distributions_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='managerlabourdistribution',
            name='manager_fund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='core.managerfund'),
        ),
        migrations.AddConstraint(
            model_name='managerfund',
            constraint=models.CheckConstraint(check=models.Q(('fund_amount__gt', 0)), name='managerfund_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='managerlabourdistribution',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='managerlabourdistribution_amount_positive'),
        ),
    ]
