# Generated by Django 4.2.30 on 2026-09-20 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


DEFAULTS = {
    'canUploadBill': {'ADMIN': True, 'OWNER': True, 'MANAGER': False, 'VIEWER': False},
    'canViewBill': {'ADMIN': True, 'OWNER': True, 'MANAGER': False, 'VIEWER': False},
}


def seed_bill_permissions(apps, schema_editor):
    RolePermission = apps.get_model('core', 'RolePermission')
    for permission, roles in DEFAULTS.items():
        for role, allowed in roles.items():
            RolePermission.objects.get_or_create(role=role, permission=permission, defaults={'allowed': allowed})


def unseed_bill_permissions(apps, schema_editor):
    apps.get_model('core', 'RolePermission').objects.filter(permission__in=list(DEFAULTS)).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_manager_fund_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('VIEWER', 'Viewer')], max_length=20)),
                ('permission', models.CharField(max_length=50)),
                ('allowed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['permission', 'role'],
            },
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='bill_content_type',
            field=models.CharField(blank=True, default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='bill_filename',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='bill_path',
            field=models.CharField(blank=True, default='', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='bill_size',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='bill_uploaded_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='bill_uploaded_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='unique_role_permission'),
        ),
        migrations.RunPython(seed_bill_permissions, unseed_bill_permissions),
    ]
