# Generated by Django 4.2.30 on 2026-09-24 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_supplier_bill_and_role_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.CharField(choices=[('ALLOW', 'Allow'), ('DENY', 'Deny')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_superadmin', models.BooleanField(default=False, help_text='Bypasses all permission checks everywhere.')),
                ('is_system', models.BooleanField(default=False, help_text='Seeded role; cannot be deleted from the UI.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='e.g. ROLE_PERMISSION_CHANGED, USER_ACCESS_GRANTED', max_length=50)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ResourcePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('group', models.CharField(blank=True, help_text='UI accordion group id (view/ops/project/...).', max_length=30)),
                ('label', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, help_text='Plain-language tooltip text.', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('GLOBAL', 'Global'), ('PROJECT', 'Project')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        # ProjectOwner/ProjectManager are dropped later (0009_rbac_backfill_and_drop_legacy), after
        # their data has been backfilled into UserAccess -- not here, so a fresh apply against an
        # environment that still has real rows in those tables never loses them.
        migrations.AddField(
            model_name='useraccess',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='core.project'),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_access', to='core.accessrole'),
        ),
        migrations.AddField(
            model_name='useraccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcepermission',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permissions', to='core.action'),
        ),
        migrations.AddField(
            model_name='resourcepermission',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permissions', to='core.resource'),
        ),
        migrations.AddField(
            model_name='permissionauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissionauditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessoverride',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessoverride',
            name='resource_permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='core.resourcepermission'),
        ),
        migrations.AddField(
            model_name='accessoverride',
            name='user_access',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='core.useraccess'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='resource_permission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='core.resourcepermission'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role_fk',
            field=models.ForeignKey(blank=True, db_column='role_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='core.accessrole'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role_fk'], name='core_rolepe_role_id_5506ef_idx'),
        ),
        migrations.AddIndex(
            model_name='useraccess',
            index=models.Index(fields=['user', 'project'], name='core_userac_user_id_7e0241_idx'),
        ),
        migrations.AddConstraint(
            model_name='useraccess',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('user', 'project'), name='unique_user_project_access'),
        ),
        migrations.AddConstraint(
            model_name='useraccess',
            constraint=models.UniqueConstraint(condition=models.Q(('scope_type', 'GLOBAL')), fields=('user',), name='unique_user_global_access'),
        ),
        migrations.AddConstraint(
            model_name='useraccess',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('project__isnull', True), ('scope_type', 'GLOBAL')), models.Q(('project__isnull', False), ('scope_type', 'PROJECT')), _connector='OR'), name='useraccess_scope_matches_project'),
        ),
        migrations.AddIndex(
            model_name='accessoverride',
            index=models.Index(fields=['user_access'], name='core_access_user_ac_77a7b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='accessoverride',
            constraint=models.UniqueConstraint(fields=('user_access', 'resource_permission'), name='unique_override'),
        ),
    ]
