# Generated by Django 4.2.30 on 2026-09-25 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rbac_notnull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='PLANNED', max_length=20),
        ),
    ]
