# Generated by Django 4.2.30 on 2026-09-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_fix_stale_permission_strings'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='managerfund',
            index=models.Index(fields=['project', 'fund_date'], name='core_manage_project_49b66e_idx'),
        ),
    ]
