# Generated by Django 4.2.30 on 2026-09-25 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_managerfund_core_manage_project_49b66e_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerfund',
            name='cancel_reason',
            field=models.TextField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='managerfund',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='managerfund',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_funds_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='managerfund',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
    ]
